<?php
/**
 * @file andes.module
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_block().
 */
function andes_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $blocks[0]['info'] = t('Block 1');
      // OPTIONAL: Add additional block descriptions here, if required.
      return $blocks;
    case 'view':
      if ($delta == 0) {
        $block['subject'] = t('Block 1 title');
        $block['content'] = _andes_display_content_block();
      }
      // OPTIONAL: Enter additional cases for each additional block, if defined.

      return $block;
  }    
}


function _andes_display_content_block() {
  $sql = "SELECT nid FROM {node} ORDER BY created DESC LIMIT 0,1";  
  $nid = db_result(db_query($sql));
  $node = node_load($nid);
  //dsm($node);
  switch($node->type){
    case 'page': $output = "page ultimo"; break;
    case 'story': $output = "story ultimo"; break;
    }
  return $output;
  }



/*

function _andes_display_content_block() {
  $sql = "SELECT nid FROM {node} ORDER BY created DESC LIMIT 0,1";  
  $nid = db_result(db_query($sql));
  $node = node_load($nid);
  dsm($node);
  switch($node->type_resource){
    case 'Video': $output = "Video"; break;
    case 'Audio': $output =  "audio"; break;  
    case 'publicación': $output =  "publicacion"; break;  
      
    }
  return $output;
  }
*/

function _andes_get_tabs($node){
//dsm($node);
$tabs['first'] = array(
  'title' => t('What we do'),
  'type' => 'freetext',
  'text' => $node->body
  );

$tabs['second'] = array(
  'title' => t('Environmental Description'),
  'type' => 'freetext',
  'text' => $node->field_desc_ambiental[0]['value']
  );

$tabs['third'] = array(
  'title' => t('Description Social'),
  'type' => 'freetext',
  'text' => $node->field_desc_social[0]['value']
);
if (isset($node->field_desc_geografica[0])){
$tabs['fourth'] = array(
  'title' => t('Geography'),
  'type' => 'freetext',
  'text' => $node->field_desc_geografica[0]['value']
);
}

if (isset($node->field_related_investigadores[0]['nid'])){
$tabs['fifth'] = array(
 'title' => t('Actors'),
  'type' => 'view',
  'vid' => 'cuencas',
  'display' => 'page_4',
  'args' => $node->nid,
);
}

$quicktabs['qtid'] = 'tabs-cuencas';
$quicktabs['tabs'] = $tabs;
$quicktabs['style'] = 'Basic';
$quicktabs['ajax'] = FALSE;
return theme('quicktabs', $quicktabs);  
}

function andes_related_nodes($items) {
  foreach ($items as $k => $v) {
    $node = node_load($v['nid']);
    $items[] = l($node->title, 'node/' . $node->nid);
  }
  print theme('item_list', $items);
}



//$node->field_related_novedades
